import type {
  AddOnOption,
  CharacterSheetItem,
  CheckItem,
  PricingPlan,
  Project,
  StickerPhrase,
  SubscriptionPlan,
  WorkflowStep,
} from "@/lib/types";

export const mockProject: Project = {
  id: "magic-rabbit-vol-1",
  name: "魔法うさぎスタンプ Vol.1",
  studioName: "Magic Rabbit Studio",
  status: "review_ready",
  stickerCount: 24,
  textMode: "hybrid",
  zipSizeEstimateMb: 3.2,
};

export const mockWorkflowSteps: WorkflowStep[] = [
  { id: 1, label: "企画入力", status: "done" },
  { id: 2, label: "キャラシート生成", status: "done" },
  { id: 3, label: "スタンプセット生成", status: "active" },
  { id: 4, label: "自動切り出し", status: "pending" },
  { id: 5, label: "ZIP書き出し", status: "pending" },
];

export const mockCharacterSheet: CharacterSheetItem[] = [
  {
    id: "front",
    label: "正面",
    angle: "front",
    description: "帽子とオレンジのマントを見せる基本ポーズ。",
  },
  {
    id: "diagonal",
    label: "斜め",
    angle: "diagonal",
    description: "顔と衣装の印象を保った斜め前ポーズ。",
  },
  {
    id: "side",
    label: "横向き",
    angle: "side",
    description: "耳、帽子、マントの横方向シルエット確認。",
  },
  {
    id: "back",
    label: "後ろ",
    angle: "back",
    description: "後ろ姿でも同一キャラクターに見える参照。",
  },
  {
    id: "expressions",
    label: "表情差分",
    angle: "expressions",
    description: "笑顔、眠い、驚き、感謝の表情差分。",
  },
  {
    id: "palette",
    label: "カラーパレット",
    angle: "palette",
    description: "白、ピンク、オレンジ、赤、黒を基調に統一。",
    palette: ["#ffffff", "#ffb3bd", "#06c755", "#00b900", "#171717"],
  },
];

export const mockStickerPhrases: StickerPhrase[] = [
  { id: 1, text: "おはよう", emotion: "元気", pose: "杖を振る", prop: "☀️" },
  { id: 2, text: "こんにちは", emotion: "笑顔", pose: "手を振る", prop: "✨" },
  { id: 3, text: "こんばんは", emotion: "落ち着き", pose: "月を見上げる", prop: "🌙" },
  { id: 4, text: "おやすみ", emotion: "眠い", pose: "枕を抱く", prop: "💤" },
  { id: 5, text: "ありがとう", emotion: "感謝", pose: "花を持つ", prop: "💛" },
  { id: 6, text: "よろしく", emotion: "丁寧", pose: "おじぎ", prop: "🎩" },
  { id: 7, text: "了解です", emotion: "前向き", pose: "敬礼", prop: "✅" },
  { id: 8, text: "OKです", emotion: "軽快", pose: "親指を立てる", prop: "👌" },
  { id: 9, text: "おつかれさま", emotion: "労い", pose: "マグを持つ", prop: "☕" },
  { id: 10, text: "ごめんね", emotion: "反省", pose: "耳を下げる", prop: "💧" },
  { id: 11, text: "大丈夫？", emotion: "心配", pose: "のぞき込む", prop: "？" },
  { id: 12, text: "いってきます", emotion: "元気", pose: "ドアから出る", prop: "🚪" },
  { id: 13, text: "いってらっしゃい", emotion: "応援", pose: "見送る", prop: "👋" },
  { id: 14, text: "ただいま", emotion: "安心", pose: "ドアを開ける", prop: "🏠" },
  { id: 15, text: "おかえり", emotion: "歓迎", pose: "両手を広げる", prop: "💗" },
  { id: 16, text: "おめでとう", emotion: "祝福", pose: "クラッカー", prop: "🎉" },
  { id: 17, text: "がんばって", emotion: "応援", pose: "杖で星を出す", prop: "⭐" },
  { id: 18, text: "ファイト！", emotion: "熱意", pose: "拳を上げる", prop: "🔥" },
  { id: 19, text: "助かります", emotion: "感謝", pose: "胸に手を当てる", prop: "✨" },
  { id: 20, text: "すごい！", emotion: "驚き", pose: "跳ねる", prop: "🌟" },
  { id: 21, text: "やったー！", emotion: "喜び", pose: "ジャンプ", prop: "🎊" },
  { id: 22, text: "またね", emotion: "柔らかい", pose: "手を振る", prop: "👋" },
  { id: 23, text: "お願いします", emotion: "依頼", pose: "おじぎ", prop: "🙏" },
  { id: 24, text: "承知です", emotion: "丁寧", pose: "メモを取る", prop: "✅" },
  { id: 25, text: "ありがとうございます", emotion: "感謝", pose: "花束", prop: "💐" },
  { id: 26, text: "すみません", emotion: "恐縮", pose: "帽子を持つ", prop: "💧" },
  { id: 27, text: "ちょっと待って", emotion: "急ぎ", pose: "時計を見る", prop: "⏳" },
  { id: 28, text: "確認します", emotion: "集中", pose: "虫眼鏡", prop: "🔍" },
  { id: 29, text: "最高！", emotion: "満足", pose: "星を掲げる", prop: "⭐" },
  { id: 30, text: "いいね", emotion: "賛成", pose: "親指を立てる", prop: "👍" },
  { id: 31, text: "無理せずに", emotion: "気遣い", pose: "毛布を渡す", prop: "☁️" },
  { id: 32, text: "休憩しよう", emotion: "休息", pose: "お茶を置く", prop: "🍵" },
  { id: 33, text: "予定あります", emotion: "連絡", pose: "カレンダー", prop: "📅" },
  { id: 34, text: "後で送ります", emotion: "実務", pose: "封筒", prop: "✉️" },
  { id: 35, text: "もう一回", emotion: "お願い", pose: "杖でリピート", prop: "🔁" },
  { id: 36, text: "完了です", emotion: "報告", pose: "チェックカード", prop: "✅" },
  { id: 37, text: "共有します", emotion: "実務", pose: "紙を渡す", prop: "📎" },
  { id: 38, text: "よろしくお願いします", emotion: "丁寧", pose: "深いおじぎ", prop: "🎩" },
  { id: 39, text: "返信します", emotion: "連絡", pose: "ペンを持つ", prop: "✒️" },
  { id: 40, text: "また明日", emotion: "穏やか", pose: "月に手を振る", prop: "🌙" },
];

export const mockCheckResults: CheckItem[] = [
  { id: "png", label: "PNG", status: "pass" },
  { id: "transparent", label: "背景透過", status: "pass" },
  { id: "stamp-size", label: "370×320以内", status: "pass" },
  { id: "even-px", label: "偶数px", status: "pass" },
  { id: "under-1mb", label: "1MB以内", status: "pass" },
  { id: "zip", label: "ZIP 60MB以内", status: "pass" },
  { id: "main", label: "メイン画像 240×240", status: "pass" },
  { id: "tab", label: "タブ画像 96×74", status: "pass" },
  {
    id: "padding",
    label: "余白 約10px",
    description: "切り出し後の絵柄周辺に約10pxの余白を確保します。",
    status: "pass",
  },
  {
    id: "ads",
    label: "広告表現なし",
    description: "商品発売告知や企業ロゴのみの構成を避けます。",
    status: "pass",
  },
  { id: "visibility", label: "視認性OK", status: "pass" },
  { id: "daily", label: "日常会話向け", status: "pass" },
];

export const mockOneShotPlans: PricingPlan[] = [
  {
    id: "trial-8",
    name: "8個お試し",
    stickerCount: 8,
    price: 980,
    description: "はじめての試作や小さな検証に。",
    features: ["キャラシート生成", "8個スタンプ", "PNG書き出し", "ZIP書き出し"],
    includedRegenerations: 2,
  },
  {
    id: "light-16",
    name: "16個ライト",
    stickerCount: 16,
    price: 1480,
    description: "日常会話の基本セットを作りたい方向け。",
    features: ["キャラシート生成", "16個スタンプ", "PNG書き出し", "ZIP書き出し"],
    includedRegenerations: 3,
  },
  {
    id: "standard-24",
    name: "24個標準",
    stickerCount: 24,
    price: 2480,
    popular: true,
    description: "販売前提の初回セットにちょうどよい構成。",
    features: [
      "キャラシート生成",
      "24個スタンプ",
      "PNG書き出し",
      "ZIP書き出し",
      "Creators Market自動チェック",
    ],
    includedRegenerations: 5,
  },
  {
    id: "extended-32",
    name: "32個拡張",
    stickerCount: 32,
    price: 3480,
    description: "表情や用途を増やしたいクリエイター向け。",
    features: ["キャラシート生成", "32個スタンプ", "PNG書き出し", "ZIP書き出し"],
    includedRegenerations: 6,
  },
  {
    id: "full-40",
    name: "40個フル",
    stickerCount: 40,
    price: 4980,
    description: "シリーズ化や本格販売前の仕上げに。",
    features: [
      "キャラシート生成",
      "40個スタンプ",
      "PNG書き出し",
      "ZIP書き出し",
      "高品質チェック",
    ],
    includedRegenerations: 8,
  },
];

export const mockAddOnOptions: AddOnOption[] = [
  {
    id: "extra-10",
    name: "追加生成10回",
    priceLabel: "980円",
    description: "表情やポーズの別案を追加で試せます。",
  },
  {
    id: "quality",
    name: "高品質モード",
    priceLabel: "+1,000円",
    description: "プロンプトを長めに使い、細部を丁寧に生成します。",
  },
  {
    id: "text-overlay",
    name: "文字あと乗せ高精度",
    priceLabel: "+500円",
    description: "読みやすい日本語文字の配置を重視します。",
  },
  {
    id: "human-review",
    name: "人間レビュー",
    priceLabel: "+3,000円",
    description: "審査前の見落としを制作目線で確認します。",
  },
  {
    id: "business-review",
    name: "法人・商用レビュー",
    priceLabel: "問い合わせ",
    description: "店舗や法人利用向けの権利・表現確認です。",
  },
];

export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: "creator-lite",
    name: "Creator Lite",
    priceMonthly: 1980,
    description: "個人クリエイターの継続制作に。",
    exportLimit: "月1セット書き出し",
    credits: 20,
    features: ["月1セット書き出し", "20生成クレジット", "キャラ保存", "ZIP書き出し"],
  },
  {
    id: "creator-pro",
    name: "Creator Pro",
    priceMonthly: 4980,
    description: "複数シリーズを回す制作者向け。",
    exportLimit: "月5セット書き出し",
    credits: 80,
    recommended: true,
    features: [
      "月5セット書き出し",
      "80生成クレジット",
      "文字あと乗せ",
      "優先処理",
      "テンプレート保存",
    ],
  },
  {
    id: "studio",
    name: "Studio",
    priceMonthly: 14800,
    description: "制作代行・店舗・法人チーム向け。",
    exportLimit: "月20セット書き出し",
    credits: 250,
    features: [
      "月20セット書き出し",
      "250生成クレジット",
      "チーム共有",
      "クライアント別管理",
      "優先サポート",
    ],
  },
];
